### ISSUE TITLE
为什么我的小助手一打开就卡住然后崩溃，运行库有下是最新的小助手版本3.0.8.5

### ISSUE THREAD

**Issue by SskadiM** [CrazyZhang666/GTA5OnlineTools#639]

**Comment by CrazyZhang666** [comment]
C:\ProgramData\GTA5OnlineTools
把这个文件夹清空，然后再打开小助手

**Comment by SskadiM** [comment]
清空了，但是还是卡住崩溃这是啥问题

**Comment by CrazyZhang666** [comment]
C:\ProgramData\GTA5OnlineTools\Log
把这个目录下 Crash文件夹下 崩溃日志发这里

**Comment by SskadiM** [comment]
![63f1d9af18842a7d75443d1a5cc43ea](https://user-images.githubusercontent.com/124445433/216772390-85e68b15-ab56-4265-9140-b37dc4b09078.jpg)
卡在这里然后过了几秒就崩溃了

**Comment by CrazyZhang666** [comment]
发日志啊 要不然我也不知道为啥崩溃

**Comment by SskadiM** [comment]
[#Crash#20230204_22-14-18_0955.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608839/Crash.20230204_22-14-18_0955.log)
[#Crash#20230204_22-14-25_4281.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608840/Crash.20230204_22-14-25_4281.log)
[#Crash#20230204_22-14-25_4298.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608841/Crash.20230204_22-14-25_4298.log)
[#Crash#20230204_22-12-10_7797.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608842/Crash.20230204_22-12-10_7797.log)
[#Crash#20230204_22-12-10_7814.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608843/Crash.20230204_22-12-10_7814.log)
[#Crash#20230204_22-14-18_0934.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608844/Crash.20230204_22-14-18_0934.log)

**Comment by SskadiM** [comment]
先谢谢作者大大了

**Comment by CrazyZhang666** [comment]
收到反馈 正在处理 等我马上发布更新

**Comment by SskadiM** [comment]
行，作者大大辛苦了

**Comment by CrazyZhang666** [comment]
https://t.wss.ink/f/af9h0bfr2f8 复制链接到浏览器打开
试试这个版本 看看会不会崩溃

**Comment by CrazyZhang666** [comment]
我重新编译的版本 文叔叔连接 下载打开试试看

**Comment by SskadiM** [comment]
[#Crash#20230204_22-32-17_5606.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608870/Crash.20230204_22-32-17_5606.log)
[#Crash#20230204_22-32-17_5589.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10608871/Crash.20230204_22-32-17_5589.log)
还是不行

**Comment by CrazyZhang666** [comment]
你目前能用的版本是哪个？

**Comment by CrazyZhang666** [comment]
加我QQ吧 1763577579

**Comment by SskadiM** [comment]
好

**Comment by CrazyZhang666** [comment]
加我QQ吧 1763575579 这个才是 头像和我一样 CrazyZhang

**Comment by SskadiM** [comment]
哦哦

**Comment by thatCbin** [comment]
===================================
【当前版本】：3.0.8.6
【编译时间】：2023/2/4 22:51:44
【操作建议】：请将此日志发送到小助手Discord频道
===================================
【出现时间】：2023/2/5 15:46:16
【异常类型】：HttpRequestException
【异常信息】：The SSL connection could not be established, see inner exception.
【堆栈调用】：
   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at GTA5OnlineTools.Helper.HttpHelper.DownloadString(String url)
   at GTA5OnlineTools.Views.HomeView.GetNoticeInfo()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at GTA5OnlineTools.App.Main()

**Comment by thatCbin** [comment]
===================================
【当前版本】：3.0.8.6
【编译时间】：2023/2/4 22:51:44
【操作建议】：请将此日志发送到小助手Discord频道
===================================
【出现时间】：2023/2/5 15:46:16
【异常类型】：HttpRequestException
【异常信息】：The SSL connection could not be established, see inner exception.
【堆栈调用】：
   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at GTA5OnlineTools.Helper.HttpHelper.DownloadString(String url)
   at GTA5OnlineTools.Views.HomeView.GetNoticeInfo()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by CrazyZhang666** [comment]
> # ===================================
> 【当前版本】：3.0.8.6
> 【编译时间】：2023/2/4 22:51:44
> 【操作建议】：请将此日志发送到小助手Discord频道
> 【出现时间】：2023/2/5 15:46:16 【异常类型】：HttpRequestException 【异常信息】：The SSL connection could not be established, see inner exception. 【堆栈调用】： at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response) at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken) at GTA5OnlineTools.Helper.HttpHelper.DownloadString(String url) at GTA5OnlineTools.Views.HomeView.GetNoticeInfo() at System.Threading.Tasks.Task.<>c.b__128_0(Object state) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

你重新下载最新版本看看，还有没有闪退问题，3.0.8.7

**Comment by thatCbin** [comment]
@CrazyZhang666 可以了

**Comment by CrazyZhang666** [comment]
ok
